/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tamagochi;

import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author lab-ibm
 */
public class Vista extends javax.swing.JFrame {

       String nombrePerro="";
       int comer = 1;
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombrePerro = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnComer = new javax.swing.JButton();
        btnEjercicio = new javax.swing.JButton();
        tfAsignaNombre = new javax.swing.JTextField();
        btnAceptarNombre = new javax.swing.JButton();
        imgPerro = new javax.swing.JLabel();
        lblIngresaNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(152, 230, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(114, 203, 237));
        jLabel1.setFont(new java.awt.Font("Capture it", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("PrImO Tamagochi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 25, 234, -1));

        lblNombrePerro.setBackground(new java.awt.Color(177, 85, 147));
        lblNombrePerro.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        lblNombrePerro.setForeground(new java.awt.Color(254, 254, 254));
        jPanel1.add(lblNombrePerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 60, 133, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 287, 83, 59));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 72, 83, 59));

        btnComer.setText("Comer");
        btnComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComerActionPerformed(evt);
            }
        });
        jPanel1.add(btnComer, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 145, 83, 59));

        btnEjercicio.setText("Ejercicio");
        btnEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjercicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 210, 83, 59));

        tfAsignaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAsignaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(tfAsignaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 217, 197, 36));

        btnAceptarNombre.setText("Aceptar");
        btnAceptarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 271, -1, -1));

        imgPerro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.gif"))); // NOI18N
        jPanel1.add(imgPerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 331, -1));

        lblIngresaNombre.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        lblIngresaNombre.setForeground(new java.awt.Color(254, 254, 254));
        lblIngresaNombre.setText("Ingresa el nombre");
        jPanel1.add(lblIngresaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 145, 175, 66));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuarto.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por jugar con " + nombrePerro + " ahora esta mas feliz");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        if (comer >= 3 )
        {
            ImageIcon imageIcon = new ImageIcon ("gatoGrande.gif");
            imgPerro.setIcon(imageIcon);
        }else{
        ImageIcon imageIcon = new ImageIcon ("inicio.gif");
        imgPerro.setIcon(imageIcon);
        }
        
        
    }//GEN-LAST:event_btnHomeActionPerformed

       @SuppressWarnings("empty-statement")
    private void btnComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComerActionPerformed
        if (comer >= 3 )
        {
            JOptionPane.showMessageDialog(null,"Tu gatito ahora es un adulto, ve a home para verlo");
        }else{
            ImageIcon imageIcon = new ImageIcon ("comer.gif");
            imgPerro.setIcon(imageIcon);
            comer++;
        }
    }//GEN-LAST:event_btnComerActionPerformed

    private void btnEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjercicioActionPerformed
        ImageIcon imageIcon = new ImageIcon ("ejercicio.gif");
        imgPerro.setIcon(imageIcon);
    }//GEN-LAST:event_btnEjercicioActionPerformed

    private void btnAceptarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNombreActionPerformed
        // TODO add your handling code here:
        nombrePerro = tfAsignaNombre.getText();
        if (!nombrePerro.equals(""))
        {
            lblNombrePerro.setText(nombrePerro);
            tfAsignaNombre.setVisible(false);
            btnAceptarNombre.setVisible(false);
            lblIngresaNombre.setVisible(false);
        }else
        JOptionPane.showMessageDialog(null,"Error, su cadena esta vacia");
    }//GEN-LAST:event_btnAceptarNombreActionPerformed

    private void tfAsignaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAsignaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAsignaNombreActionPerformed

    public static void ejecutar() {
                new Vista().setVisible(true);
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarNombre;
    private javax.swing.JButton btnComer;
    private javax.swing.JButton btnEjercicio;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgPerro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIngresaNombre;
    private javax.swing.JLabel lblNombrePerro;
    private javax.swing.JTextField tfAsignaNombre;
    // End of variables declaration//GEN-END:variables
}
