
import javax.swing.JOptionPane;

/**
 * En esta clase se manejan todos los componentes (botones, campos de texto, etc)
 * @author primo
 * @version 1.0 06/10/2015
 */

public class Vista extends javax.swing.JFrame {

    double numero1;
    double numero2;
    double resultado;
    
    //Esta parte es para darle formato de salida al resultado de 3 decimales despues del punto.
    java.text.DecimalFormat Salida = new java.text.DecimalFormat("0.000");//para dos decimales
    /**
     * Crea una nueva vista
     */
    public Vista() {
        initComponents();
        this.setTitle("Calculadora Básica");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRestar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        tfNumero1 = new javax.swing.JTextField();
        tfNumero2 = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 111, 111));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 251, 251));
        jLabel1.setText("Bienvenido a PrImO Calculator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 330, 50));

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 207, 102, 75));

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 207, 102, 75));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 207, 102, 75));

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 207, 102, 75));

        tfNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero1ActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 110, 150, -1));

        tfNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumero2ActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 155, 150, -1));

        tfResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(tfResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 134, 137, -1));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Ingresa los numeros a operar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 27));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Número 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 116, 68, -1));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Número 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 155, 68, 26));

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Resultado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 98, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt Evento del text field resultado
     */
    private void tfResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoActionPerformed

    }//GEN-LAST:event_tfResultadoActionPerformed

    /**
     * Este metodo realiza la multiplicacion de dos numeros reales
     * @param evt  evento del boton Sumar, iniciara la accion sumar numero 1 y numero 2
     */
    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        numero1 = Double.parseDouble(tfNumero1.getText());
        numero2 = Double.parseDouble(tfNumero2.getText());
        resultado = numero1 + numero2;
        tfResultado.setText(Salida.format(resultado));
    }//GEN-LAST:event_btnSumarActionPerformed

    /**
     * Este metodo realiza la division de dos numeros reales (el segundo diferente de 0)
     * @param evt evento del boton Dividir, iniciara la accion dividir numero 1 y numero 2
     */
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        numero1 = Double.parseDouble(tfNumero1.getText());
        numero2 = Double.parseDouble(tfNumero2.getText());

        if ( numero2 <= 0)
        {
            JOptionPane.showMessageDialog(null,"Error!, no puede dividirse entre 0!!");
        }else{
            resultado = numero1 / numero2;
            tfResultado.setText(Salida.format(resultado));
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    /**
     * Este metodo realiza la multiplicacion de dos numeros reales
     * @param evt evento del boton Multiplicar, iniciara la accion multiplicar numero 1 y numero 2
     */
    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        numero1 = Double.parseDouble(tfNumero1.getText());
        numero2 = Double.parseDouble(tfNumero2.getText());
        resultado = numero1 * numero2;
        tfResultado.setText(Salida.format(resultado));
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    /**
     * @param evt Evento del boton Numero 2
     */
    private void tfNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero2ActionPerformed

    }//GEN-LAST:event_tfNumero2ActionPerformed

    private void tfNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumero1ActionPerformed

    }//GEN-LAST:event_tfNumero1ActionPerformed

    /**
     * Este metodo realiza la multiplicacion de dos numeros reales
     * @param evt evento del boton Restar, accion restar numero 1 y numero 2
     */
    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        numero1 = Double.parseDouble(tfNumero1.getText());
        numero2 = Double.parseDouble(tfNumero2.getText());
        resultado = numero1 - numero2;
        tfResultado.setText(Salida.format(resultado));
    }//GEN-LAST:event_btnRestarActionPerformed

   
   
    /**
     * Metodo ejecutar que crea la vista, es nuestro contenedor
     */
    public static void ejecutar()
    {
        new Vista().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfNumero1;
    private javax.swing.JTextField tfNumero2;
    private javax.swing.JTextField tfResultado;
    // End of variables declaration//GEN-END:variables
}
